#!/bin/sh
#200000
./train_word2vec.py \
    --gpu 0 \
    --input_path /home/ubuntu/data/word2vec/20160920_index_sequence_min_count_32.txt \
    --index2word_path /home/ubuntu/data/word2vec/20160920_index2word_min_count_32.pkl \
    --word2index_path /home/ubuntu/data/word2vec/20160920_word2index_min_count_32.pkl \
    --counts_path /home/ubuntu/data/word2vec/20160920_counts_min_count_32.pkl \
    --train_max_path /home/ubuntu/data/word2vec/20160920_train_max_min_count_32.pkl \
    --total_size_path /home/ubuntu/data/word2vec/20160920_total_size_min_count_32.pkl \
    --unit 200 \
    --batchsize 160000 \
    --out-type ns \
    --model cbow \
    --window 8 \
    --out /home/ubuntu/results/word2vec \
    --epoch 1 

