#!/bin/sh

time ./train_word2vec.py \
    --gpu -1 \
    --input /home/ubuntu/data/word2vec/jawiki-wakati-index-sequence.txt \
    --index2word /home/ubuntu/data/word2vec/index2word.pkl \
    --word2index /home/ubuntu/data/word2vec/word2index.pkl \
    --unit 200 \
    --out-type ns \
    --model cbow \
    --window 8 \
    --epoch 1

