#!/bin/sh

./find_words.py \
        --file_path /Users/kumada/Data/image_net/images/list \
        --word2index_path /Users/kumada/Data/enwiki/20160920_word2index.pkl \
        --output_path /Users/kumada/Data/image_net/images/selected_list
