#!/bin/sh

./index_sequence_maker.py \
        --word2index_file_path /Users/kumada/Data/enwiki/20160920_word2index.pkl \
        --wiki_file_path /Users/kumada/Data/enwiki/20160920.wiki \
        --index_sequence_file_path /Users/kumada/Data/enwiki/20160920_index_sequence.txt
