#!/bin/sh

./copy_selected_image_directory.py \
        --selected_list_path /Users/kumada/Data/image_net/images/selected_list \
        --src_dir_path /Users/kumada/Data/image_net/images \
        --dst_dir_path /Users/kumada/Data/image_net/selected_images
