#!/bin/sh

./predict_similarities.py \
        --label_path /home/ubuntu/data/devise/selected_images_256_greater_than_200_images/label_selected.txt \
        --model_path /home/ubuntu/results/word2vec/word2vec.model \
        --count 5
